site_name: Upside Engine
site_author: TheHackerPuppy
site_description: >- 
  Upside Engine is the perfect tool to create your own 2d game in roblox!
repo_name: TheHackerPuppy/UpsideEngine
repo_url: https://github.com/TheHackerPuppy/UpsideEngine
use_directory_urls: false
edit_uri: edit/docs/docs/

theme:
  name: material
  docs_dir: docs
  custom_dir: overrides
  logo: assets/logo.png
  favicon: assets/logo.png
  icon:
    repo: fontawesome/brands/github-alt
  font: false

  features:
  - navigation.instant
  - navigation.tracking
  - navigation.tabs
  - navigation.indexes
  - navigation.top
  - content.tabs.link
  - content.code.copy
  - content.action.edit
  - content.action.view
  - navigation.footer
  - search.suggest
  - toc.integrate

  palette:
  - scheme: default
    primary: white
    accent: black
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode

  - scheme: slate
    primary: indigo
    accent: white
    toggle:
      icon: material/weather-night
      name: Switch to light mode

  plugins:
  - offline

nav:
  - Home: index.md

  - Games: "games.md"

  - Tutorials: 
    - Welcome: tutorials/Welcome.md
    
    - Getting Started: 
      - Installation: tutorials/get-started/Installation.md
      - Your first game: tutorials/get-started/FirstGame.md
      - Player Character: tutorials/get-started/PlayerCharacter.md
      - Music: tutorials/get-started/Music.md
      
      - Graphic inteface: tutorials/get-started/GraphicInterface.md
      - License: tutorials/get-started/LicensePage.md

    - Style Guide:
      - Project Structure: tutorials/style-guide/ProjectStructure.md
      - Module Structure: tutorials/style-guide/ModuleStructure.md
      - Module Management: tutorials/style-guide/ModuleManagement.md

    - Plugin Guide: 
      - First steps: tutorials/plugin-guide/FirstSteps.md
      - Using tile editor: tutorials/plugin-guide/TileEditor.md
      - Using sprite editor: tutorials/plugin-guide/SpriteEditor.md
      - Using collision editor: tutorials/plugin-guide/CollisionEditor.md
      - Plugin Scripts: tutorials/plugin-guide/PluginScripts.md

    - Multiplayer Integration: 
      - Client Side: tutorials/multiplayer-game/client.md
      - Server Side: tutorials/multiplayer-game/server.md

    - Shader Guide: 
      - First Steps: tutorials/shader-guide/FirstSteps.md
      - Basic effect: tutorials/shader-guide/BasicEffect.md
      - Integrated Functions: tutorials/shader-guide/IntegratedFunctions.md

    - Assets with AI: 
      - Introduction: tutorials/ai-assets/Introduction.md
      - Steps: tutorials/ai-assets/Steps.md
      
  - Documentation:
    - Welcome: documentation/Welcome.md
    - Upside Engine: documentation/UpsideEngine.md
    
    - Classes:
      - BaseClass: documentation/BaseClass.md
      - BaseObject: documentation/autogen/BaseObject.md
      - Camera: documentation/autogen/Camera.md
      - Character: documentation/autogen/Character.md
      - Connection: documentation/autogen/Connection.md
      - Environment: documentation/autogen/Environment.md
      - EventEmitter: documentation/autogen/EventEmitter.md
      - Light: documentation/autogen/Light.md
      - LightingEnvironment: documentation/autogen/LightingEnvironment.md
      - SoundEnvironment: documentation/autogen/SoundEnvironment.md
      - ShaderEnvironment: documentation/autogen/ShaderEnvironment.md
      - Particle: documentation/autogen/Particle.md
      - PhysicalObject: documentation/autogen/PhysicalObject.md
      - StaticObject: documentation/autogen/StaticObject.md
      - Request: documentation/autogen/Request.md
      - Scene: documentation/autogen/Scene.md
      - Sound: documentation/autogen/Sound.md
      - Sprite: documentation/autogen/Sprite.md
      - Shader: documentation/autogen/Shader.md
      - Fluid: documentation/autogen/Fluid.md
      - Parallax: documentation/autogen/Parallax.md
    - Services:
      - CrossPlatformService: documentation/autogen/CrossPlatformService.md
      - PluginSupportService: documentation/autogen/PluginSupportService.md
      - NetworkingService: documentation/autogen/NetworkingService.md
      - SceneManager: documentation/autogen/SceneManager.md
    - DataTypes:
      - UpsideEngineInput: "documentation/datatypes/UpsideEngineInput.md"
      - Raycast2DParams: "documentation/datatypes/Raycast2DParams.md"
      - Raycast2DResult: "documentation/datatypes/Raycast2DResult.md"

extra:
  social:
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/UpsideEngine
    - icon: fontawesome/brands/youtube 
      link: https://www.youtube.com/channel/UCoi8my88QdaB0xt4Z49RO3g
    - icon: fontawesome/brands/discord 
      link: https://discord.com/invite/pE3svUvmnu

extra_css: 
  - stylesheet/extra.css

markdown_extensions:
  - attr_list
  - md_in_html
  - abbr
  - admonition
  - footnotes
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.keys
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      title: On this page
      permalink_title: Anchor link to this section for reference
      toc_depth: 3
      permalink: true
      