name: release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install aftman
        run: |
          curl -L https://github.com/LPGhatguy/aftman/releases/download/v0.3.0/aftman-0.3.0-linux-x86_64.zip -o aftman.zip
          unzip aftman.zip -d aftman-bin
          ./aftman-bin/aftman self-install
          echo "$HOME/.aftman/bin" >> $GITHUB_PATH

      - run: aftman install

      - run: rojo build default.project.json --output UpsideEngine.rbxm

      - uses: softprops/action-gh-release@v2
        with:
          files: UpsideEngine.rbxm
