name: release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ok-nick/setup-aftman@v0.4.2

      - run: aftman install

      - run: rojo build default.project.json --output UpsideEngine.rbxm

      - uses: softprops/action-gh-release@v2
        with:
          files: UpsideEngine.rbxm
